import streamlit as st
import random
import re
import time
from openai import AzureOpenAI, APIError, APIConnectionError, RateLimitError

# Configure sensitive patterns and replacements
SENSITIVE_PATTERNS = {
    r"\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b": 'IP_ADDRESS="XXX.XXX.XXX.XXX"',
    r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b": 'EMAIL="***@***.com"',
    r"\b(?:\d{4}-?){3}\d{4}\b": 'CREDIT_CARD="****-****-****-****"',
    r"\b\d{3}-\d{2}-\d{4}\b": 'SSN="***-**-****"',
}

SENSITIVE_KEYWORDS = ["token", "password", "secret", "api key", "credentials"]

def filter_sensitive_content(prompt):
    """Filter and mask sensitive information in the prompt"""
    masked_prompt = prompt
    for pattern, replacement in SENSITIVE_PATTERNS.items():
        masked_prompt = re.sub(pattern, replacement, masked_prompt, flags=re.IGNORECASE)
    
    if any(keyword in masked_prompt.lower() for keyword in SENSITIVE_KEYWORDS):
        return None
    
    return masked_prompt if masked_prompt != prompt else prompt

# Streamlit UI Configuration
st.set_page_config(page_title="Config-Manager AI", page_icon="🚀")
title_style = "color: #001C7B; font-weight: bold;"
st.markdown(f"<h1 style='{title_style}'>💬 🚀🚀 Config-Manager AI 🚀🚀</h1>", unsafe_allow_html=True)

# Sidebar Configuration
with st.sidebar:
    st.title("Configuration")
    modules = [
        "ansible Playbook jinja2 template",
        "ansible Playbook yaml file",  
        "yaml script", 
        "python script", 
        "shell script", 
        "docker file", 
        "kubernetes yaml file", 
        "juypter notebook",
        "Windows PowerShell",
        "terraform script",
    ]
    selected_module = st.selectbox("Select Module", modules)
    st.caption("Powered by Azure OpenAI LLM")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "assistant", "content": "How can I assist you with script generation today?"}]

# Display chat messages
for msg in st.session_state.messages:
    st.chat_message(msg["role"]).write(msg["content"])

# Chat input processing
if prompt := st.chat_input("Enter your configuration request:"):
    # Input validation
    if len(prompt) > 1000:
        st.warning("Input exceeds maximum length of 1000 characters. Please shorten your message.")
        st.stop()
    
    # Content filtering
    filtered_prompt = filter_sensitive_content(prompt)
    if not filtered_prompt:
        st.warning("Input contains sensitive content. Please revise and try again.")
        st.stop()

    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": filtered_prompt})
    st.chat_message("user").write(filtered_prompt)

    try:
        # Initialize Azure OpenAI client with error handling
        client = AzureOpenAI(
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT", "https://codedocumentation.openai.azure.com/"),
            api_key=os.getenv("AZURE_OPENAI_KEY", "sjdhfshdjfhshjhsdgh"),
            api_version="2024-02-15-preview"
        )

        # Add context to the request
        context_messages = st.session_state.messages.copy()
        context_messages.append({"role": "system", "content": f"Generate {selected_module} configuration"})

        # API call with retry logic
        max_retries = 3
        response = None
        
        for attempt in range(max_retries):
            try:
                with st.spinner(f"Generating response (attempt {attempt+1}/{max_retries})..."):
                    response = client.chat.completions.create(
                        model="gpt-4o-mini",
                        messages=context_messages,
                        temperature=0.3,
                        max_tokens=1000
                    )
                    break
            except (APIConnectionError, RateLimitError) as e:
                if attempt == max_retries - 1:
                    raise
                time.sleep(2 ** attempt)  # Exponential backoff

        # Validate response
        if not response or not response.choices:
            raise APIError("Received empty response from the API")
        
        msg = response.choices[0].message.content
        
        if not msg.strip():
            raise ValueError("Empty response generated by the model")

        # Add assistant response to chat history
        st.session_state.messages.append({"role": "assistant", "content": msg})
        st.chat_message("assistant").write(msg)

    except (APIError, APIConnectionError, RateLimitError) as e:
        error_msg = f"⚠️ API Error: {str(e)}. Please try again later."
        st.session_state.messages.append({"role": "assistant", "content": error_msg})
        st.chat_message("assistant").write(error_msg)
        st.stop()
        
    except Exception as e:
        error_msg = f"⚠️ Unexpected error: {str(e)}. Please contact support."
        st.session_state.messages.append({"role": "assistant", "content": error_msg})
        st.chat_message("assistant").write(error_msg)
        st.stop()

# Add footer with additional information
st.sidebar.markdown("---")
st.sidebar.caption(f"Session ID: {random.randint(10000, 99999)}")
st.sidebar.caption("v1.2.0 | Secured AI System")
